# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.57.0"

default_platform :ios

platform :ios do
  before_all do
    ensure_git_status_clean
    ensure_git_branch(branch:'fastlane')
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Publish a build to S3"
  lane :adhoc do
    match(type:'adhoc')
    gym
    s3(
      region:'us-west-2',
      bucket:'pi-ios-apps',
      html_file_name:'pano.html',
      version_file_name:'pano.json',
      path:'fastlane/HPPano/v{CFBundleShortVersionString}_b{CFBundleVersion}/'
    )
    # http://hpgo.co/X8hZhE
  end

  desc "Build an ipa file for HP Inc."
  lane :hp do
    gym(
      configuration:'HP Inc.',
      output_name:'HPPano.HPInc.ipa',
      codesigning_identity:'iPhone Distribution: HP Inc.',
      provisioning_profile_path:"#{ENV['HOME']}/Library/MobileDevice/Provisioning Profiles/1a0943ba-4246-437c-a435-2b179bdbef91.mobileprovision"
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
